export interface PermissionCatalogItem {
  code: string;
  labelFa: string;
  descriptionFa: string;
  category: 'ERP_ACADEMIC' | 'LMS' | 'OPERATIONS' | 'FINANCE' | 'RBAC';
  categoryFa: string;
  isSensitive: boolean;
  icon: string;
}

export const PERMISSION_CATEGORIES: {
  key: 'ERP_ACADEMIC' | 'LMS' | 'OPERATIONS' | 'FINANCE' | 'RBAC';
  nameFa: string;
  descriptionFa: string;
  icon: string;
}[] = [
  {
    key: 'ERP_ACADEMIC',
    nameFa: 'آموزشی و ساختار مدرسه (ERP)',
    descriptionFa: 'مدیریت دروس، پایه‌ها، رشته‌ها، کلاس‌ها، و پرونده دانش‌آموزان و اساتید',
    icon: 'GraduationCap',
  },
  {
    key: 'LMS',
    nameFa: 'سنجش و آزمون (LMS)',
    descriptionFa: 'طراحی آزمون‌ها، تصحیح، بانک سوالات، ثبت نمرات و کارنامه تحصیلی',
    icon: 'BarChart3',
  },
  {
    key: 'OPERATIONS',
    nameFa: 'عملیات و تعاملات روزانه',
    descriptionFa: 'حضور و غیاب کلاسی، تکالیف درسی، تقویم و رویدادها، کوچینگ و رسانه',
    icon: 'CalendarDays',
  },
  {
    key: 'FINANCE',
    nameFa: 'امور مالی و حقوق و دستمزد',
    descriptionFa: 'مدیریت شهریه‌ها، اقساط، پرداختی‌ها و حقوق پرسنل (دسترسی حساس)',
    icon: 'Receipt',
  },
  {
    key: 'RBAC',
    nameFa: 'مدیریت نقش‌ها و دسترسی‌ها',
    descriptionFa: 'ایجاد نقش‌های جدید، تخصیص مجوزها و پیکربندی امنیتی مدرسه',
    icon: 'ShieldCheck',
  },
];

export const PERMISSION_CATALOG: PermissionCatalogItem[] = [
  // 1. ERP & Academic
  {
    code: 'academic.year.read',
    labelFa: 'مشاهده سال و دوره‌های تحصیلی',
    descriptionFa: 'امکان مشاهده تقویم سالانه، ترم‌ها و دوره‌های آموزشی تعریف‌شده',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Calendar',
  },
  {
    code: 'academic.year.write',
    labelFa: 'مدیریت سال و ترم‌های تحصیلی',
    descriptionFa: 'امکان تعریف یا ویرایش سال تحصیلی و بازه‌های زمانی ترم‌ها',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Calendar',
  },
  {
    code: 'academic.level.write',
    labelFa: 'مدیریت مقاطع و پایه‌ها',
    descriptionFa: 'امکان تعریف پایه‌های تحصیلی (دهم، یازدهم، دوازدهم)',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Layers',
  },
  {
    code: 'academic.field.write',
    labelFa: 'مدیریت رشته‌های تحصیلی',
    descriptionFa: 'امکان ایجاد و ویرایش رشته‌های فنی، ریاضی، تجربی و...',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Compass',
  },
  {
    code: 'lesson.read',
    labelFa: 'مشاهده لیست دروس و سرفصل‌ها',
    descriptionFa: 'امکان مشاهده مشخصات، واحدها و عناوین کتاب‌ها و پودمان‌های درسی',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'BookOpen',
  },
  {
    code: 'lesson.write',
    labelFa: 'تعریف و اصلاح دروس',
    descriptionFa: 'امکان افزودن درس جدید، تغییر تعداد واحد و پودمان‌های کتاب‌ها',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'BookOpen',
  },
  {
    code: 'classroom.read',
    labelFa: 'مشاهده کلاس‌ها و اعضا',
    descriptionFa: 'امکان مشاهده اسامی کلاس‌ها، ظرفیت و لیست دانش‌آموزان حاضر',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Building2',
  },
  {
    code: 'classroom.write',
    labelFa: 'ایجاد و ویرایش کلاس‌های درس',
    descriptionFa: 'امکان تشکیل کلاس جدید، تعیین معلم راهنما و تغییر ظرفیت کلاس',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Building2',
  },
  {
    code: 'schedule.read',
    labelFa: 'مشاهده برنامه هفتگی',
    descriptionFa: 'امکان مشاهده جدول زمان‌بندی زنگ‌های هفتگی کلاس‌ها و اساتید',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Clock',
  },
  {
    code: 'schedule.write',
    labelFa: 'تنظیم و ویرایش برنامه هفتگی',
    descriptionFa: 'امکان چیدمان ساعات آموزشی، تغییر ساعت تدریس اساتید و تداخل‌گیری',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Clock',
  },
  {
    code: 'enrollment.write',
    labelFa: 'انتساب دانش‌آموزان به کلاس',
    descriptionFa: 'امکان ثبت‌نام دانش‌آموز در کلاس درس یا جابجایی بین کلاس‌ها',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'UserPlus',
  },
  {
    code: 'student.read',
    labelFa: 'مشاهده پرونده دانش‌آموزان',
    descriptionFa: 'امکان مشاهده اطلاعات هویتی، تماس و وضعیت تحصیلی دانش‌آموزان',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Users',
  },
  {
    code: 'student.write',
    labelFa: 'ثبت‌نام و ویرایش دانش‌آموز',
    descriptionFa: 'امکان افزودن دانش‌آموز جدید، ویرایش کد ملی، تلفن و وضعیت فعال/راکد',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'UserPlus',
  },
  {
    code: 'teacher.read',
    labelFa: 'مشاهده مشخصات هنرآموزان و اساتید',
    descriptionFa: 'امکان مشاهده فهرست اساتید، سوابق تحصیلی، دروس تخصصی و اطلاعات تماس',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'UserCheck',
  },
  {
    code: 'teacher.write',
    labelFa: 'مدیریت و ثبت اساتید جدید',
    descriptionFa: 'امکان استخدام، تعریف پرونده دبیر و انتساب دروس به اساتید',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'UserCheck',
  },
  {
    code: 'coach.read',
    labelFa: 'مشاهده مشخصات کوچ‌ها و مربیان',
    descriptionFa: 'امکان مشاهده مربیان هدایت و مشاوره به همراه دانش‌آموزان تحت نظر',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Target',
  },
  {
    code: 'coach.write',
    labelFa: 'مدیریت مربیان و کوچ‌ها',
    descriptionFa: 'امکان تعریف و فعال‌سازی مربیان مشاوره در ساختار مدرسه',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Target',
  },
  {
    code: 'staff.read',
    labelFa: 'مشاهده کادر اجرایی و اداری',
    descriptionFa: 'امکان مشاهده مشخصات پرسنل اداری، ناظمین و معاونین هنرستان',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Users',
  },
  {
    code: 'staff.write',
    labelFa: 'مدیریت کادر اجرایی و اداری',
    descriptionFa: 'امکان افزودن یا ویرایش پرونده همکاران بخش اداری و اجرایی',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Users',
  },
  {
    code: 'parent.read',
    labelFa: 'مشاهده اطلاعات والدین',
    descriptionFa: 'امکان مشاهده مشخصات پدر و مادر دانش‌آموزان و شماره‌های اضطراری',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'HeartHandshake',
  },
  {
    code: 'parent.write',
    labelFa: 'مدیریت اطلاعات والدین',
    descriptionFa: 'امکان ثبت شماره همراه و اطلاعات هویتی اولیاء در پرونده',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'HeartHandshake',
  },
  {
    code: 'parent.student.link',
    labelFa: 'اتصال ولی به فرزند',
    descriptionFa: 'امکان تعیین نسبت خانوادگی و پیوند حساب کاربری والدین به دانش‌آموز',
    category: 'ERP_ACADEMIC',
    categoryFa: 'آموزشی و ساختار مدرسه (ERP)',
    isSensitive: false,
    icon: 'Link',
  },

  // 2. LMS & Grades
  {
    code: 'exam.read',
    labelFa: 'مشاهده آزمون‌ها و سوالات',
    descriptionFa: 'امکان مشاهده تقویم امتحانات، بارم‌بندی و سوالات آزمون‌های آنلاین و حضوری',
    category: 'LMS',
    categoryFa: 'سنجش و آزمون (LMS)',
    isSensitive: false,
    icon: 'HelpCircle',
  },
  {
    code: 'exam.write',
    labelFa: 'طراحی و برگزاری آزمون',
    descriptionFa: 'امکان ساخت آزمون جدید، تنظیم کلید سوالات و انتشار برای کلاس',
    category: 'LMS',
    categoryFa: 'سنجش و آزمون (LMS)',
    isSensitive: false,
    icon: 'HelpCircle',
  },
  {
    code: 'grades.read',
    labelFa: 'مشاهده نمرات و کارنامه‌ها',
    descriptionFa: 'امکان مشاهده ریزنمرات، معدل‌ها، نمرات پودمانی و کارنامه جامع دانش‌آموزان',
    category: 'LMS',
    categoryFa: 'سنجش و آزمون (LMS)',
    isSensitive: false,
    icon: 'BarChart3',
  },
  {
    code: 'grades.write',
    labelFa: 'ثبت و ویرایش نمرات (دفتر نمره)',
    descriptionFa: 'امکان ورود نمره مستمر، نمره پایانی، نمرات پودمانی و تصحیح کارنامه‌ها',
    category: 'LMS',
    categoryFa: 'سنجش و آزمون (LMS)',
    isSensitive: false,
    icon: 'BarChart3',
  },

  // 3. Operations & Daily
  {
    code: 'attendance.read',
    labelFa: 'مشاهده گزارش حضور و غیاب',
    descriptionFa: 'امکان بررسی تاریخچه تاخیرها، غیبت‌ها و وضعیت روزانه حضور در کلاس',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'UserCheck',
  },
  {
    code: 'attendance.write',
    labelFa: 'ثبت حضور و غیاب روزانه',
    descriptionFa: 'امکان ثبت تاخیر، غیبت موجه/غیرموجه و حضور کلاسی دانش‌آموزان',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'UserCheck',
  },
  {
    code: 'homework.read',
    labelFa: 'مشاهده تکالیف و تحویل‌ها',
    descriptionFa: 'امکان مشاهده فایل‌های ارسال‌شده توسط دانش‌آموزان و متن تکالیف',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'FileCheck',
  },
  {
    code: 'homework.write',
    labelFa: 'تعریف و نمره‌دهی تکالیف',
    descriptionFa: 'امکان ارسال تکلیف کلاسی جدید، تعیین مهلت ارسال و بازخورد کیفی/کمی',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'FileCheck',
  },
  {
    code: 'calendar.write',
    labelFa: 'مدیریت تقویم و رویدادهای سالانه',
    descriptionFa: 'امکان افزودن رویدادها، وبینارها، جلسات عمومی و تعطیلات در تقویم',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'CalendarDays',
  },
  {
    code: 'coaching.read',
    labelFa: 'مشاهده پرونده و جلسات کوچینگ',
    descriptionFa: 'امکان مشاهده جلسات دوهفته‌ای، وضعیت مشارکت و تاریخچه مشاوره‌ها',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'Target',
  },
  {
    code: 'coaching.write',
    labelFa: 'مدیریت جلسات و یادداشت‌های کوچینگ',
    descriptionFa: 'امکان انتساب مربی، ثبت حضور در جلسه مشاوره، ثبت یادداشت و پاسخ به درخواست فوق‌العاده',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'Target',
  },
  {
    code: 'blog.write',
    labelFa: 'انتشار پست در رسانه هنرستان',
    descriptionFa: 'امکان انتشار مقالات، اخبار، دستاوردها و رسانه‌های عمومی آموزشگاه',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'Sparkles',
  },
  {
    code: 'blog.publish',
    labelFa: 'تایید و انتشار نهایی اخبار',
    descriptionFa: 'امکان تایید انتشار پست‌ها و نظارت بر کامنت‌ها در رسانه آموزشگاه',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'Sparkles',
  },
  {
    code: 'school.profile.write',
    labelFa: 'ویرایش پروفایل و مشخصات مدرسه',
    descriptionFa: 'امکان تغییر آدرس، لوگو، درباره ما، شعار و کادر معرفی هنرستان',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'Building2',
  },
  {
    code: 'message.broadcast',
    labelFa: 'ارسال پیام همگانی به همه کاربران',
    descriptionFa: 'امکان ارسال پیام گروهی به کل مدرسه، همه اساتید، همه دانش‌آموزان یا همه اولیاء',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'Megaphone',
  },
  {
    code: 'message.class.write',
    labelFa: 'ارسال پیام گروهی به کلاس',
    descriptionFa: 'امکان ارسال پیام و بخشنامه به دانش‌آموزان و اولیای کلاس‌های آموزشی',
    category: 'OPERATIONS',
    categoryFa: 'عملیات و تعاملات روزانه',
    isSensitive: false,
    icon: 'MessageSquare',
  },

  // 4. Finance (⚠️ Sensitive)
  {
    code: 'finance.fee.read',
    labelFa: 'مشاهده صورت‌حساب‌ها و شهریه‌ها',
    descriptionFa: 'امکان بررسی بدهی، فیش‌های واریزی و اقساط پرداخت‌شده دانش‌آموزان',
    category: 'FINANCE',
    categoryFa: 'امور مالی و حقوق و دستمزد',
    isSensitive: true,
    icon: 'Receipt',
  },
  {
    code: 'finance.fee.write',
    labelFa: 'تعریف مبالغ شهریه و ثبت واریزی‌ها',
    descriptionFa: 'امکان صدور پیش‌فاکتور، تخفیف، قسط‌بندی و ثبت تایید فیش بانکی',
    category: 'FINANCE',
    categoryFa: 'امور مالی و حقوق و دستمزد',
    isSensitive: true,
    icon: 'Receipt',
  },
  {
    code: 'finance.check.manage',
    labelFa: 'مدیریت و تغییر وضعیت چک‌ها',
    descriptionFa: 'امکان ثبت وصول، برگشت، تعویض چک‌های دریافتی و تغییر وضعیت اسناد بهادار',
    category: 'FINANCE',
    categoryFa: 'امور مالی و حقوق و دستمزد',
    isSensitive: true,
    icon: 'FileCheck',
  },
  {
    code: 'finance.fee.import',
    labelFa: 'ورود گروهی اطلاعات مالی از اکسل',
    descriptionFa: 'امکان تخصیص گروهی شهریه و ثبت دسته‌جمعی پرداخت‌های نقدی و چک از طریق فایل اکسل',
    category: 'FINANCE',
    categoryFa: 'امور مالی و حقوق و دستمزد',
    isSensitive: true,
    icon: 'FileSpreadsheet',
  },
  {
    code: 'finance.payroll.read',
    labelFa: 'مشاهده فیش‌های حقوق و دستمزد',
    descriptionFa: 'امکان مشاهده احکام حقوقی، کسورات و فیش‌های دستمزد اساتید و پرسنل',
    category: 'FINANCE',
    categoryFa: 'امور مالی و حقوق و دستمزد',
    isSensitive: true,
    icon: 'Wallet',
  },
  {
    code: 'finance.payroll.write',
    labelFa: 'محاسبه و پرداخت حقوق پرسنل',
    descriptionFa: 'امکان ورود ساعات کارکرد، اضافه کار، پاداش و تایید حواله حقوقی',
    category: 'FINANCE',
    categoryFa: 'امور مالی و حقوق و دستمزد',
    isSensitive: true,
    icon: 'Wallet',
  },

  // 5. RBAC & Roles (⚠️ Highly Sensitive)
  {
    code: 'role.read',
    labelFa: 'مشاهده نقش‌ها و سطوح دسترسی',
    descriptionFa: 'امکان مشاهده لیست نقش‌های سازمانی مدرسه و مجوزهای هر نقش',
    category: 'RBAC',
    categoryFa: 'مدیریت نقش‌ها و دسترسی‌ها',
    isSensitive: false,
    icon: 'Shield',
  },
  {
    code: 'role.write',
    labelFa: 'ساخت و ویرایش نقش‌های سازمانی',
    descriptionFa: 'امکان تعریف نقش جدید (مثل ناظم، مشاور) و چیدمان پرمیشن‌های آن',
    category: 'RBAC',
    categoryFa: 'مدیریت نقش‌ها و دسترسی‌ها',
    isSensitive: true,
    icon: 'Sliders',
  },
  {
    code: 'role.assign',
    labelFa: 'تخصیص نقش به اعضای مدرسه',
    descriptionFa: 'امکان انتساب یا سلب نقش‌های ایجادشده به اساتید و کارکنان',
    category: 'RBAC',
    categoryFa: 'مدیریت نقش‌ها و دسترسی‌ها',
    isSensitive: true,
    icon: 'UserCheck',
  },
  {
    code: 'rbac.manage',
    labelFa: 'مدیریت تام و اورراید دسترسی‌ها (کلان)',
    descriptionFa: 'دسترسی کامل به سازنده نقش، اوررایدهای موردی کاربران و پیکربندی امنیتی',
    category: 'RBAC',
    categoryFa: 'مدیریت نقش‌ها و دسترسی‌ها',
    isSensitive: true,
    icon: 'ShieldCheck',
  },
];
